baseURL = "https://lovelybuggies.github.io/notes/"
languageCode = "en-us"
title = "LovelyBuggies' Blog"
enableGitInfo = true
cleanDestinationDir = true

# Publish the built site into the repo at /notes
publishDir = "../notes"

# Use a local theme (no Go/Hugo Modules required)
theme = "book"

[params]
  BookTheme = "auto"
  BookToC = true
  BookSearch = false
  BookRepo = "https://github.com/LovelyBuggies/LovelyBuggies.github.io"
  BookDateFormat = "Jan 2, 2006"
  BookSection = "docs"
  # Use custom favicon for the site
  BookFavicon = "myicon.svg"
  # Show page last modified time (needs enableGitInfo)
  ShowLastMod = true
  # Enable KaTeX for math rendering across the site
  BookMath = true

[markup]
  [markup.smartypants]
    quotes = false
    dashes = ""
    ellipses = false
    fractions = false
    angledQuotes = false
  [markup.highlight]
    style = "github"
    noClasses = false
  [markup.goldmark.extensions]
    typographer = false
  [markup.goldmark.renderer]
    unsafe = true
